version: "3.6"
services:
  elasticsearch:
    image: elasticsearch:7.9.3
    container_name: elasticsearch-container
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - elastic
    ports:
      - 9200:9200
  kibana:
    image: kibana:7.9.3
    container_name: kibana-container
    networks:
      - elastic
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
networks:
  elastic:
    driver: bridge
